In [ ]:
# Sowjanya Sunkavalli
# 700731896

## Programming elements:
## Classification

## Question 1

### 1. Find the correlation between ‘survived’ (target column) and ‘sex’ column for the Titanic use case in class.

In [30]:
import numpy as np # Importing numpy as np
import pandas as pd # Importing pandas as pd
import warnings # Importing warnings to exclude warnings 
warnings.filterwarnings("ignore")

In [ ]:
train = pd.read_csv('train.csv') # Reading train data set as train dataframe
test = pd.read_csv('test.csv') # Reading test data set as test dataframe

In [17]:
train['Sex'] = train['Sex'].replace(["female", "male"], [1, 0]) # Replacing Female and Male values with 1 , 0 
train['Embarked'] = train['Embarked'].replace(['S','C','Q'],[0,1,2]) # Replacing S, C, QA with 0, 1, 2

In [18]:
train.fillna(train.mean(),axis=0,inplace=True) # Filling null values with mean

In [19]:
train['Survived'].corr(train['Sex']) # Correlation of train for Survived and Sex

0.5433513806577552

### a. Do you think we should keep this feature?

In [ ]:
# Yes

### 2. Do at least two visualizations to describe or show correlations
###  Showing correlations

In [20]:
# showing correlations for trained data set with background style and color
train.corr().style.background_gradient(cmap="Greys") 

### 3. Implement Naïve Bayes method using scikit-learn library and report the accuracy.

In [21]:
X = train.drop(columns = ['Name','Survived','Ticket','Cabin']) # Dropping alphnumeric values
Y = train[['Survived']] # assigning Survived column

In [22]:
# Splitting dataset into traning and testing data sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) 

In [23]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB() #creating the model
classifier.fit(X_train, Y_train) #Feeding training data to the model

Y_pred = classifier.predict(X_test) # Predicting the test variables

# Summary of the predictions made by the classifier
print(classification_report(Y_test, Y_pred)) # Classification report 
print(confusion_matrix(Y_test, Y_pred)) # confusion matrix
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(Y_pred,Y_test)) # Accuracy of the model

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       110
           1       0.72      0.75      0.74        69

    accuracy                           0.79       179
   macro avg       0.78      0.79      0.78       179
weighted avg       0.80      0.79      0.79       179

[[90 20]
 [17 52]]
accuracy is 0.7932960893854749


## Question 2

### Implement Naive Bayes method using scikit-learn library.
### a. Use the glass dataset available in Link also provided in your assignment

In [24]:
data = pd.read_csv('glass.csv') # reading glass data set as data

In [25]:
X = data.drop(columns=['Type']) # dropping Type coloumn
Y = data['Type'] # assigning type column

### b. Use train_test_split to create training and testing part.

In [26]:
# Splitting dataset into traning and testing data sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) 

### 2. Evaluate the model on testing part using score and classification_report

In [35]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB # importing classifier
classifier = GaussianNB() # assigning classifier with model
classifier.fit(X_train, Y_train) # feeding training data to the model

Y_pred = classifier.predict(X_test) # Predicting the dependant variable
# Summary of the predictions made by the classifier
print(classification_report(Y_test, Y_pred)) # Classification Report
print(confusion_matrix(Y_test, Y_pred)) # Confusion matrix
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(Y_pred,Y_test)) # Finding the Accuracy

              precision    recall  f1-score   support

           1       0.19      0.44      0.27         9
           2       0.33      0.16      0.21        19
           3       0.33      0.20      0.25         5
           5       0.00      0.00      0.00         2
           6       0.67      1.00      0.80         2
           7       1.00      1.00      1.00         6

    accuracy                           0.37        43
   macro avg       0.42      0.47      0.42        43
weighted avg       0.40      0.37      0.36        43

[[ 4  3  1  0  1  0]
 [14  3  1  1  0  0]
 [ 3  1  1  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]
accuracy is 0.37209302325581395


### 1. Implement linear SVM method using scikit library

In [37]:
# Support Vector Machine's 
from sklearn.svm import SVC # importing SVC 
classifier = SVC() # creating the model
classifier.fit(X_train, Y_train) # feeding model with training dataset
Y_pred = classifier.predict(X_test) # predicting the dependent variable in the test dataset


### 2. Evaluate the model on testing part using score and Classification

In [38]:
# Summary of the predictions made by the classifier
print(classification_report(Y_test, Y_pred)) # printing the classification report
print(confusion_matrix(Y_test, Y_pred)) # printing the confusion matrix
# Accuracy score
from sklearn.metrics import accuracy_score # importing the accuracy_score
print('accuracy is',accuracy_score(Y_pred,Y_test)) # printing the accuracy of predicted values with true values

              precision    recall  f1-score   support

           1       0.21      1.00      0.35         9
           2       0.00      0.00      0.00        19
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         6

    accuracy                           0.21        43
   macro avg       0.03      0.17      0.06        43
weighted avg       0.04      0.21      0.07        43

[[ 9  0  0  0  0  0]
 [19  0  0  0  0  0]
 [ 5  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 6  0  0  0  0  0]]
accuracy is 0.20930232558139536


### Do at least two visualizations to describe or show correlations in the Glass Dataset.
### Showing Correlations

In [29]:
data.corr().style.background_gradient(cmap="Greys") # Correlation for trained data set

### Which algorithm you got better accuracy? Can you justify why?

In [ ]:
# After analyzing results got from training data with Naives Bayes and SVM model, from the above results of accuracy 
# We can say Naives Bayes Algorithm is better than SVM
# Accuracy of Naive Bayes i.e 37.2% > Accuracy of SVM i.e 20.9%